// Generated by CoffeeScript 1.6.2
var $, Backbone, Pane, Tabs, View, register, _ref, _ref1, _ref2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

$ = require('jqueryify');

Backbone = require('backbone');

_ref = require('../lib/index'), register = _ref.register, View = _ref.View;

Pane = (function(_super) {
  __extends(Pane, _super);

  function Pane() {
    _ref1 = Pane.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  Pane.prototype.render = function() {
    return this.$el.html(this.options.text);
  };

  return Pane;

})(Backbone.View);

register('pane', Pane);

Tabs = (function(_super) {
  __extends(Tabs, _super);

  function Tabs() {
    _ref2 = Tabs.__super__.constructor.apply(this, arguments);
    return _ref2;
  }

  Tabs.registerAs('tabs');

  return Tabs;

})(View);
