// Generated by CoffeeScript 1.6.2
var $, Pane, View, register, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

$ = require('jqueryify');

View = require('backbone').View;

register = require('../lib/index').register;

Pane = (function(_super) {
  __extends(Pane, _super);

  function Pane() {
    _ref = Pane.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Pane.prototype.render = function() {
    console.log(this.options);
    return this.$el.html(this.options.text);
  };

  return Pane;

})(View);

register('pane', Pane);
